LogLevel = "DEBUG"
ServerAddress = "127.0.0.1:3005"
JWTSecretkey = "TestIv8^vow%Jf4gPfppyt*q"
ProfilePhotoDir = "./data/profile/photo"

[MysqlConfig]
User = "root"
Passwd = "gonghuan"
DBName = "uolo"
HostPort = "127.0.0.1:3306"
