LogLevel = "DEBUG"
ServerAddress = "127.0.0.1:3006"
JWTSecretkey = "TestIv8^vow%Jf4gPfppyt*q"
PostDataDir = "./data/"


[MysqlConfig]
User = "fake"
Passwd = "fake"
DBName = "lens"
HostPort = "0.0.0.0:3300"


