LogLevel = "DEBUG"
ServerAddress = "127.0.0.1:3006"
JWTSecretkey = "TestIv8^vow%Jf4gPfppyt*q"
PostDataDir = "./data/"


[MysqlConfig]
User = "root"
Passwd = "gonghuan"
DBName = "uolo"
HostPort = "127.0.0.1:3306"

[[RedisConfig]]
Name    = "recommend"
Addr     = "127.0.0.1:6379"
DbIndex  = 0
Password = ""